import json
import os
import argparse
import cumulative_transience

def main():
    parser = argparse.ArgumentParser(description="Generate a transient analysis report for audio files in a directory.")
    parser.add_argument("--dir", default=".", help="Directory containing audio files (default: current directory)")
    parser.add_argument("--output", default="transient_analysis.html", help="Output HTML file name (default: transient_analysis.html)")
    args = parser.parse_args()

    # Supported audio extensions
    extensions = ('.wav', '.mp3', '.m4a', '.flac', '.ogg', '.aiff')
    audio_files = [f for f in os.listdir(args.dir) if f.lower().endswith(extensions)]
    audio_files.sort()

    if not audio_files:
        print(f"No audio files found in {os.path.abspath(args.dir)}")
        return

    all_data = {}
    for f in audio_files:
        file_path = os.path.join(args.dir, f)
        result = cumulative_transience.analyze_audio(file_path)
        if result:
            all_data[f] = result
            cumulative_transience.generate_video(file_path, result)

    if not all_data:
        print("No valid audio data was processed.")
        return

    html_template = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transient Analysis Report</title>
    <!-- Using Plotly.js for interactive visualizations -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; line-height: 1.6; color: #333; background-color: #f9f9f9; }
        .container { max-width: 1200px; margin: auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; text-align: center; }
        .controls { margin-bottom: 30px; padding: 20px; background: #ecf0f1; border-radius: 5px; }
        .controls label { font-weight: bold; display: block; margin-bottom: 10px; }
        #file-select { width: 100%; padding: 10px; font-size: 16px; border-radius: 4px; border: 1px solid #ccc; }
        #audio-player { width: 100%; margin-top: 20px; }
        #graph { width: 100%; height: 400px; margin-top: 20px; }
        #buffer-graph { width: 100%; height: 400px; margin-top: 20px; }
        #ssm-graph { width: 100%; height: 600px; margin-top: 30px; }
        .footnote { margin-top: 20px; padding: 15px; background: #fdf6e3; border-left: 5px solid #b58900; font-size: 14px; color: #586e75; }
        .footnote h3 { margin-top: 0; color: #b58900; }
        .math-block { font-family: "Courier New", Courier, monospace; background: #eee; padding: 10px; border-radius: 4px; margin-top: 10px; overflow-x: auto; }
        .footer { margin-top: 40px; font-size: 12px; text-align: center; color: #7f8c8d; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Transient Analysis Report</h1>

        <div class="controls">
            <label for="file-select">Select Audio File:</label>
            <select id="file-select"></select>

            <audio id="audio-player" controls></audio>
        </div>

        <div id="graph"></div>
        <div id="buffer-graph"></div>
        <div id="ssm-graph"></div>
        <div id="ssm-footnote" class="footnote"></div>

        <div class="footer">
            Generated by Transient Analysis Tool
        </div>
    </div>

    <script>
        const data = DATA_PLACEHOLDER;
        const fileSelect = document.getElementById('file-select');
        const audioPlayer = document.getElementById('audio-player');
        const graphDiv = document.getElementById('graph');
        const bufferDiv = document.getElementById('buffer-graph');
        const ssmDiv = document.getElementById('ssm-graph');
        const footnoteDiv = document.getElementById('ssm-footnote');

        let accumulatedBuffer = new Array(5001).fill(0);
        let processedPeaks = new Set();
        let cleanedPeaks = new Set();
        let peakSnapshots = {}; // peakIdx -> snapshot
        let activeFlashes = []; // {snapshot: [], lifetime: 20}
        let lastFrameIdx = -1;

        const bufferTimes = [];
        for (let i = -5000; i <= 0; i++) bufferTimes.push(i);

        // Populate dropdown with available audio files
        Object.keys(data).forEach(filename => {
            const option = document.createElement('option');
            option.value = filename;
            option.textContent = filename;
            fileSelect.appendChild(option);
        });

        let currentFile = fileSelect.value;

        function updateGraph(filename) {
            const fileData = data[filename];

            const traceTransient = {
                x: fileData.times,
                y: fileData.onset_env,
                mode: 'lines',
                name: 'Transient Envelope',
                line: { color: '#3498db', width: 2 },
                hoverinfo: 'x+y'
            };

            const tracePeaks = {
                x: fileData.peaks.times,
                y: fileData.peaks.values,
                mode: 'markers',
                name: 'Peaks',
                marker: { color: '#e74c3c', size: 8, symbol: 'cross' },
                hoverinfo: 'x+y'
            };

            const layout = {
                title: {
                    text: 'Transient Analysis - ' + filename,
                    font: { size: 18 }
                },
                xaxis: { title: 'Time (seconds)', gridcolor: '#eee' },
                yaxis: { title: 'Onset Strength (Energy Flux)', gridcolor: '#eee' },
                plot_bgcolor: '#fff',
                paper_bgcolor: '#fff',
                shapes: [{
                    type: 'line',
                    x0: 0,
                    x1: 0,
                    y0: 0,
                    y1: 1,
                    yref: 'paper',
                    line: {
                        color: '#e67e22',
                        width: 2,
                        dash: 'dash'
                    },
                    name: 'playhead'
                }, {
                    type: 'line',
                    x0: -15,
                    x1: -15,
                    y0: 0,
                    y1: 1,
                    yref: 'paper',
                    line: {
                        color: '#9b59b6',
                        width: 2,
                        dash: 'dot'
                    },
                    name: 'cleanup'
                }],
                dragmode: 'zoom',
                hovermode: 'closest',
                showlegend: true,
                legend: { x: 1, xanchor: 'right', y: 1 }
            };

            const config = {
                responsive: true,
                displaylogo: false
            };

            Plotly.newPlot(graphDiv, [traceTransient, tracePeaks], layout, config);

            // Initialize Buffer Graph
            const traceBuffer = {
                x: bufferTimes,
                y: accumulatedBuffer,
                mode: 'lines',
                name: 'Accumulated Buffer',
                line: { color: '#2ecc71', width: 2 },
                fill: 'tozeroy'
            };

            const bufferLayout = {
                title: 'Accumulated 5s Historical Buffer (Real-time)',
                xaxis: { title: 'Time Relative to Peak (ms)' },
                yaxis: { title: 'Accumulated Energy', autorange: true },
                plot_bgcolor: '#fff',
                paper_bgcolor: '#fff'
            };

            Plotly.newPlot(bufferDiv, [traceBuffer], bufferLayout, config);

            // Update SSM Visualization using Base64 Image
            const ssmExtent = fileData.ssm_extent;

            // Dummy trace to establish axes
            const ssmTrace = {
                x: ssmExtent,
                y: ssmExtent,
                mode: 'markers',
                marker: { opacity: 0 },
                showlegend: false,
                hoverinfo: 'none'
            };

            // Dummy trace for colorbar
            const colorbarTrace = {
                x: [null],
                y: [null],
                type: 'scatter',
                mode: 'markers',
                marker: {
                    colorscale: 'Viridis',
                    cmin: 0,
                    cmax: 1,
                    showscale: true,
                    colorbar: {
                        title: 'Similarity',
                        thickness: 20,
                        len: 0.9,
                        yanchor: 'middle',
                        y: 0.5
                    }
                },
                showlegend: false,
                hoverinfo: 'none'
            };

            const ssmLayout = {
                title: {
                    text: 'Transient Self-Similarity Matrix',
                    font: { size: 18 }
                },
                xaxis: {
                    title: 'Time (seconds)',
                    range: ssmExtent,
                    fixedrange: false
                },
                yaxis: {
                    title: 'Time (seconds)',
                    range: ssmExtent,
                    scaleanchor: 'x',
                    fixedrange: false
                },
                images: [{
                    source: 'data:image/png;base64,' + fileData.ssm_image,
                    xref: 'x',
                    yref: 'y',
                    x: ssmExtent[0],
                    y: ssmExtent[1],
                    sizex: ssmExtent[1] - ssmExtent[0],
                    sizey: ssmExtent[1] - ssmExtent[0],
                    sizing: 'stretch',
                    opacity: 1,
                    layer: 'below'
                }],
                shapes: [{
                    type: 'line',
                    x0: 0,
                    x1: 0,
                    y0: ssmExtent[0],
                    y1: ssmExtent[1],
                    xref: 'x',
                    yref: 'y',
                    line: { color: '#e67e22', width: 2, dash: 'dash' },
                    name: 'playhead-x'
                }, {
                    type: 'line',
                    y0: 0,
                    y1: 0,
                    x0: ssmExtent[0],
                    x1: ssmExtent[1],
                    xref: 'x',
                    yref: 'y',
                    line: { color: '#e67e22', width: 2, dash: 'dash' },
                    name: 'playhead-y'
                }]
            };

            Plotly.newPlot(ssmDiv, [ssmTrace, colorbarTrace], ssmLayout, config);

            // Update Footnote with Math
            const ps = fileData.peak_similarity;
            const norm_i = ps.onset_i / ps.max_onset;
            const norm_j = ps.onset_j / ps.max_onset;
            const dist = Math.abs(ps.onset_i - ps.onset_j);
            const base_similarity = 1 - (dist / ps.max_dist);
            const weight = Math.min(norm_i, norm_j);

            footnoteDiv.innerHTML = `
                <h3>Peak Off-Diagonal Similarity Analysis</h3>
                <p>The point of greatest similarity (excluding the main diagonal) occurs at <strong>t1 = ${ps.time_i.toFixed(3)}s</strong> and <strong>t2 = ${ps.time_j.toFixed(3)}s</strong>.</p>
                <div class="math-block">
                    <strong>1. Normalization:</strong><br>
                    norm_i = onset_i / max_onset = ${ps.onset_i.toFixed(4)} / ${ps.max_onset.toFixed(4)} = ${norm_i.toFixed(4)}<br>
                    norm_j = onset_j / max_onset = ${ps.onset_j.toFixed(4)} / ${ps.max_onset.toFixed(4)} = ${norm_j.toFixed(4)}<br><br>
                    <strong>2. Base Similarity:</strong><br>
                    dist = |onset_i - onset_j| = |${ps.onset_i.toFixed(4)} - ${ps.onset_j.toFixed(4)}| = ${dist.toFixed(4)}<br>
                    S_base = 1 - (dist / max_dist) = 1 - (${dist.toFixed(4)} / ${ps.max_dist.toFixed(4)}) = ${base_similarity.toFixed(4)}<br><br>
                    <strong>3. Transience Weighting:</strong><br>
                    W = min(norm_i, norm_j) = min(${norm_i.toFixed(4)}, ${norm_j.toFixed(4)}) = ${weight.toFixed(4)}<br><br>
                    <strong>4. Final Similarity:</strong><br>
                    S_final = S_base * W = ${base_similarity.toFixed(4)} * ${weight.toFixed(4)} = <strong>${ps.final_similarity.toFixed(4)}</strong>
                </div>
            `;
        }

        function updateAudio(filename) {
            // Assumes audio files are in the same relative path as the HTML report
            audioPlayer.src = filename;
            audioPlayer.load();
        }

        fileSelect.addEventListener('change', (e) => {
            currentFile = e.target.value;
            accumulatedBuffer.fill(0);
            processedPeaks.clear();
            cleanedPeaks.clear();
            peakSnapshots = {};
            lastFrameIdx = -1;
            updateGraph(currentFile);
            updateAudio(currentFile);
        });

        // Synchronize playhead on the graph with audio playback
        audioPlayer.addEventListener('timeupdate', () => {
            const currentTime = audioPlayer.currentTime;
            const fileData = data[currentFile];
            const frameIdx = Math.floor(currentTime * 1000); // 1ms resolution
            const cleanupFrameIdx = frameIdx - 15000; // 15 seconds behind

            // Reset if seeking (forward or backward to keep it simple and accurate)
            // Use 100ms threshold for reset
            if (Math.abs(frameIdx - lastFrameIdx) > 100) {
                accumulatedBuffer.fill(0);
                processedPeaks.clear();
                cleanedPeaks.clear();
                peakSnapshots = {};
            }

            // Check for peaks passed since last update
            const peakIndices = fileData.peaks.indices;
            let bufferUpdated = false;

            for (let i = 0; i < peakIndices.length; i++) {
                const peakIdx = peakIndices[i];

                // Add peak if it's passed the playhead but not the cleanup sweep
                if (peakIdx <= frameIdx && peakIdx > cleanupFrameIdx && !processedPeaks.has(peakIdx)) {
                    processedPeaks.add(peakIdx);

                    const start = peakIdx - 5000;
                    const end = peakIdx;
                    const window = new Array(5001).fill(0);

                    for (let j = 0; j <= 5000; j++) {
                        const envIdx = start + j;
                        if (envIdx >= 0 && envIdx < fileData.onset_env.length) {
                            window[j] = fileData.onset_env[envIdx];
                        }
                    }

                    const peakVal = fileData.onset_env[peakIdx];
                    const normalization = peakVal / fileData.max_peak_value;

                    const snapshot = new Array(5001);
                    for (let j = 0; j < 5001; j++) {
                        snapshot[j] = window[j] * normalization;
                        accumulatedBuffer[j] += snapshot[j];
                    }
                    peakSnapshots[peakIdx] = snapshot;
                    activeFlashes.push({snapshot: snapshot, lifetime: 20});
                    bufferUpdated = true;
                }

                // Subtract peak if it's passed the cleanup sweep
                if (peakIdx <= cleanupFrameIdx && processedPeaks.has(peakIdx) && !cleanedPeaks.has(peakIdx)) {
                    const snapshot = peakSnapshots[peakIdx];
                    if (snapshot) {
                        for (let j = 0; j < 5001; j++) {
                            accumulatedBuffer[j] -= snapshot[j];
                        }
                        delete peakSnapshots[peakIdx];
                    }
                    cleanedPeaks.add(peakIdx);
                    bufferUpdated = true;
                }
            }

            if (bufferUpdated || activeFlashes.length > 0) {
                // Handle Flash and Fade
                activeFlashes = activeFlashes.filter(f => f.lifetime > 0);
                activeFlashes.forEach(f => f.lifetime--);

                // Update Buffer Graph with Flashes and Peaks
                const traces = [
                    {
                        x: bufferTimes,
                        y: accumulatedBuffer,
                        mode: 'lines',
                        name: 'Accumulated Buffer',
                        line: { color: '#2ecc71', width: 2 },
                        fill: 'tozeroy'
                    }
                ];

                activeFlashes.forEach((f, idx) => {
                    traces.push({
                        x: bufferTimes,
                        y: f.snapshot,
                        mode: 'lines',
                        name: 'Flash ' + idx,
                        line: { color: 'rgba(46, 204, 113, ' + (f.lifetime / 20 * 0.5) + ')', width: 0 },
                        fill: 'tozeroy',
                        showlegend: false,
                        hoverinfo: 'none'
                    });
                });

                // Peak Detection in Buffer
                const shapes = [];
                const annotations = [];
                const maxVal = Math.max(...accumulatedBuffer);
                const detectedPeaks = [];
                if (maxVal > 0.01) {
                    const localMaxima = [];
                    for (let i = 1; i < accumulatedBuffer.length - 1; i++) {
                        if (accumulatedBuffer[i] > accumulatedBuffer[i-1] &&
                            accumulatedBuffer[i] > accumulatedBuffer[i+1] &&
                            accumulatedBuffer[i] > 0.01) {
                            localMaxima.push({idx: i, val: accumulatedBuffer[i]});
                        }
                    }
                    localMaxima.sort((a, b) => b.val - a.val);

                    for (let i = 0; i < localMaxima.length && detectedPeaks.length < 3; i++) {
                        const peak = localMaxima[i];
                        let tooClose = false;
                        for (const existing of detectedPeaks) {
                            if (Math.abs(existing.idx - peak.idx) < 200) {
                                tooClose = true;
                                break;
                            }
                        }
                        if (!tooClose) {
                            detectedPeaks.push(peak);
                        }
                    }
                }

                const peakStyles = [
                    { color: '#f1c40f', width: 2, opacity: 1.0 }, // 1st: Gold
                    { color: '#ecf0f1', width: 1.5, opacity: 0.9 }, // 2nd: Silver
                    { color: '#bdc3c7', width: 1, opacity: 0.8 } // 3rd: Bronze
                ];

                detectedPeaks.forEach((peak, i) => {
                    const msVal = bufferTimes[peak.idx];
                    const style = peakStyles[i] || peakStyles[2];
                    shapes.push({
                        type: 'line',
                        x0: msVal,
                        x1: msVal,
                        y0: 0,
                        y1: 1,
                        yref: 'paper',
                        line: { color: style.color, width: style.width, dash: 'dash', opacity: style.opacity }
                    });
                    annotations.push({
                        x: msVal,
                        y: 1 - (i * 0.05),
                        yref: 'paper',
                        text: msVal + 'ms',
                        showarrow: false,
                        font: { color: style.color, size: 10, weight: 'bold' },
                        bgcolor: 'rgba(0,0,0,0.5)',
                        yshift: -10
                    });
                });

                Plotly.react(bufferDiv, traces, {
                    title: 'Accumulated 5s Historical Buffer (Real-time)',
                    xaxis: { title: 'Time Relative to Peak (ms)' },
                    yaxis: { title: 'Accumulated Energy', autorange: true },
                    plot_bgcolor: '#333', // Darker background for better contrast with white lines
                    paper_bgcolor: '#fff',
                    shapes: shapes,
                    annotations: annotations
                });
            }

            lastFrameIdx = frameIdx;

            // Update Transient Graph Playhead and Range
            Plotly.relayout(graphDiv, {
                'xaxis.range': [currentTime - 20, currentTime + 5],
                'shapes[0].x0': currentTime,
                'shapes[0].x1': currentTime,
                'shapes[1].x0': currentTime - 15,
                'shapes[1].x1': currentTime - 15
            });

            // Update SSM Crosshair Playhead
            Plotly.relayout(ssmDiv, {
                'shapes[0].x0': currentTime,
                'shapes[0].x1': currentTime,
                'shapes[1].y0': currentTime,
                'shapes[1].y1': currentTime
            });
        });

        // Initial load
        if (currentFile) {
            updateGraph(currentFile);
            updateAudio(currentFile);
        }

    </script>
</body>
</html>
    """

    # Injecting data as JSON. Using json.dumps ensures proper escaping.
    report_content = html_template.replace("DATA_PLACEHOLDER", json.dumps(all_data))

    output_path = args.output
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    print(f"Report generated successfully: {os.path.abspath(output_path)}")

if __name__ == "__main__":
    main()
